on: [push, pull_request]
name: CI
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      # make sure all code has been formatted with rustfmt
      - run: rustup component add rustfmt
      - run: git submodule update --init
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check --color always

      # run clippy to verify we have no warnings
      - run: rustup component add clippy
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-features -- -D warnings

  cargo-deny:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: EmbarkStudios/cargo-deny-action@master # we use latest master as this is our own tool that we maintain

  test:
    name: Test
    strategy:
      matrix:
        os: [ubuntu-latest, windows-2019, macOS-latest]
    env:
      DEVELOPER_DIR: /Applications/Xcode_11.1.app
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - run: git submodule update --init
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features

  package:
    name: Package
    strategy:
      matrix:
        os: [ubuntu-latest, windows-2019, macOS-latest]
    env:
      DEVELOPER_DIR: /Applications/Xcode_11.1.app
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - run: git submodule update --init
      - uses: actions-rs/cargo@v1
        with:
          command: package
          args: --manifest-path ./physx-sys/Cargo.toml
